services:
  mysql:
    image: mysql:8.0.36
    ports:
      - 3306:3306
    env_file: "../.env"
    healthcheck:
      test: "mysqladmin ping -h localhost"
      interval: 1s
      timeout: 3s
      retries: 10
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
